# Turns an in-game /btdump into a version-accurate luacheck std (tools/wow-globals.lua).
#
#   1. In-game: enable "BetterTogether API Dump", run /btdump, then /reload.
#   2. pwsh tools/gen-wow-api.ps1
#   3. pwsh tools/lint.ps1   (now checks against the real client API)
#
# .luacheckrc loads tools/wow-globals.lua automatically when present, else falls back
# to its curated list, so deleting the generated file is always safe.

param(
  [string]$WowRoot = "C:\Program Files (x86)\World of Warcraft\_retail_",
  [string]$SvFile  # optional explicit path to BetterTogetherAPIDump.lua
)
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot

# Locate the SavedVariables file (newest across accounts) unless one was passed.
if (-not $SvFile) {
  $glob = Join-Path $WowRoot "WTF\Account\*\SavedVariables\BetterTogetherAPIDump.lua"
  $SvFile = Get-ChildItem -Path $glob -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $SvFile -or -not (Test-Path $SvFile)) {
  Write-Error "No BetterTogetherAPIDump.lua found. Run /btdump then /reload in-game first.`nSearched under: $WowRoot\WTF\Account\*\SavedVariables\"
}
Write-Host "Reading $SvFile" -ForegroundColor Cyan

$text = Get-Content -Raw -LiteralPath $SvFile
$m = [regex]::Match($text, '\["globals"\]\s*=\s*"([^"]*)"')
if (-not $m.Success) { Write-Error "Could not find the 'globals' field in the dump." }
$bm = [regex]::Match($text, '\["build"\]\s*=\s*"([^"]*)"')
$build = if ($bm.Success) { $bm.Groups[1].Value } else { "unknown" }

# Captured value has literal \n separators (WoW escapes newlines in SV strings).
$ids = $m.Groups[1].Value -split '\\n' | Where-Object { $_ -ne "" }

# Standard Lua libs/globals: leave these to luacheck's built-in lua51 std (keeps its
# stricter field checking for string/table/math/etc.). WoW extras (strsplit, wipe...)
# are NOT here, so they still get captured from _G.
$deny = @{}
@(
  '_G','_VERSION','assert','collectgarbage','dofile','error','getfenv','getmetatable',
  'ipairs','load','loadfile','loadstring','module','next','pairs','pcall','print',
  'rawequal','rawget','rawlen','rawset','require','select','setfenv','setmetatable',
  'tonumber','tostring','type','unpack','xpcall',
  'string','table','math','os','io','coroutine','debug'
  # NOTE: not 'bit' — luacheck's lua51 std has no bit library, so we keep WoW's from _G.
) | ForEach-Object { $deny[$_] = $true }

$plain = [System.Collections.Generic.HashSet[string]]::new()
$ns = @{}   # namespace -> HashSet of fields
foreach ($id in $ids) {
  if ($id -like 'BetterTogether*' -or $id -like 'SLASH_BTAPIDUMP*') { continue }
  $dot = $id.IndexOf('.')
  if ($dot -lt 0) {
    if (-not $deny.ContainsKey($id)) { [void]$plain.Add($id) }
  } else {
    $head = $id.Substring(0, $dot)
    $field = $id.Substring($dot + 1)
    if ($deny.ContainsKey($head)) { continue }
    if (-not $ns.ContainsKey($head)) { $ns[$head] = [System.Collections.Generic.HashSet[string]]::new() }
    [void]$ns[$head].Add($field)
  }
}
# A name that has descended fields is emitted as a namespace table, not a plain global.
foreach ($k in $ns.Keys) { [void]$plain.Remove($k) }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- AUTO-GENERATED by tools/gen-wow-api.ps1 from an in-game /btdump. Do not edit.")
[void]$sb.AppendLine("-- Client build: $build")
[void]$sb.AppendLine("return {")
[void]$sb.AppendLine("  read_globals = {")
foreach ($name in ($plain | Sort-Object)) {
  [void]$sb.AppendLine("    `"$name`",")
}
foreach ($name in ($ns.Keys | Sort-Object)) {
  $fields = ($ns[$name] | Sort-Object | ForEach-Object { "`"$_`"" }) -join ", "
  [void]$sb.AppendLine("    $name = { fields = { $fields } },")
}
[void]$sb.AppendLine("  },")
[void]$sb.AppendLine("}")

$out = Join-Path $RepoRoot "tools\wow-globals.lua"
Set-Content -LiteralPath $out -Value $sb.ToString() -Encoding UTF8 -NoNewline
Write-Host ("Wrote {0}: {1} globals + {2} namespaces (build {3})" -f $out, $plain.Count, $ns.Count, $build) -ForegroundColor Green
